### ISSUE TITLE
Fullføre implementasjon av filter på Kundesiden

### ISSUE THREAD

**Issue by henrikav** [knowit/folk-webapp#345]
**Status**
For øyeblikket er det implementert mulighet for filtrering i både `BarChart.tsx` og `LineChart.tsx` som vises på toppen av Kundesiden. Filtrene tar nå inn hardkodede reg_periods i funksjonen `findFilteredData(regPeriods?: string[])`, basert på hva som er tilgjengelig av testdata i dev. Denne implentasjonen finnes i komponenten `ChartCard.tsx`, spesifikt `SingularChartCard.tsx`. Dette er implementert i PR: [fix/fikse-konsulentvisning-kundeside](https://github.com/knowit/folk-webapp/pull/316)

**Todo**
Ønsket bruk er at funksjonen `findFilteredData(regPeriods?: string[])` skal ta inn en liste med reg_periods og filtrerer dataene i grafene basert på inneværende reg_period. Denne listen må genereres dynamisk ved hjelp av den utkommenterte funksjonen `getCurrentRegPeriod()` . På denne måten kan filtrene alltid generere en liste med riktige reg_periods.  

**NB**: Husk å sette `showFilter` til `true` inne i `HoursBilledPerWeekCard.tsx` og `HoursBilledPerCustomerCard.tsx` for at filtrene skal vises.

**Comment by mariehessen** [comment]
- Fikse sortering av x-aksen i nivo charts ([#359 Sortering av nivo charts med xScale.type: points](https://github.com/knowit/folk-webapp/issues/359))
- Implementering av design ([#381 Implementere nytt design på kundesiden som ligger på figma](https://github.com/knowit/folk-webapp/issues/381))
