### ISSUE TITLE
Feil på internprosjekt trafikklys

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#346]
Interne prosjekter skal være "blå" i Prosjektstatus kolonnen,
Men NN er blå og jobber på <prosjekt> - vedlikeholds team. og burde vært grønn siden dette er et kunde prosjekt.
NN2 er på samme prosjekt team og siden hen er "Åpen for nye prosjekter" er det vanskelig å vite om hen ellers hadde vært blå eller grønn.

**Comment by janhenrik** [comment]
Opprettes på nytt ved behov.
