### ISSUE TITLE
Kompetanse/Utdannelse

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#352]
I Folk.Knowit.no under kompetanse fliken og i utdannelses oversikten har vi bare med de som har en av de 3 nivåene: 
Phd, Master, Bachelor. 
Det hadde vært fint om vi også hadde en 4 kategori "Annen" for at vi har antall på de som ikke faller inn under de 3 øvrige kategoriene.

**Comment by matfol** [comment]
Ref. diskujsonen på standup 09.01.2023 koim vi fram til at man trengte enda en kategori 'Ikke registrert' for å dekke de tilfellene hvor man ikke har noe data for utdanning
