### ISSUE TITLE
Mangler data for hele 2022 og slutten av 2021 på "Fag og hendelser"

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#358]
**Sted**: Kompetanse / "Fag og hendelser" / 2022-2023

Det ser ut til at vi mangler data for hele 2022 og slutten av 2021.

Vet ikke om det er slutt på henting av disse data eller om det er noen funksjon som har sluttet å virke, men det ser ikke ut til at vi har data å vise.

2 stepp for å få det opp:
* sørge for at vi henter data fra UBW for denne aktiviteten
* sjekke at vi også viser data for kontinuerlig periode.
* (Mulig at vi må gjøre noe spesielt for å hente data for den perioden vi ikke har data)

Akseptansekriterier:
- Hente data til S3 fra UBW 
- Vise både 2022 data og 2023 data

![Image](https://user-images.githubusercontent.com/7239092/221868461-96d78779-aa4b-4718-a21a-e985555f11b5.png)

**Comment by henrikav** [comment]
Dataen for denne grafen hentes fra fagkalendern som ligger i Google. Denne har ikke vært vedlikeholdt på lenge og har ikke blitt videreført etter vi byttet fra Google til Microsoft. Dette iniativet er noe som muligens kommer til å være fagkalendern i fremtiden, men er ikke oppe enda: https://github.com/Knowit-Objectnet/hvaskjer-webapp
