### ISSUE TITLE
Forslag: Mer beskrivende tittel på ulike sider i Folk

### ISSUE THREAD

**Issue by thoasc** [knowit/folk-webapp#361]
OBS: behov/prioritering av denne oppgaven må avklares før den utføres.

Per i dag har alle sider tittelen "Knowit Folk". Det er altså snakk om tittelen som vises på fanen (tab-baren) i nettleseren. Dette gjør det vanskelig å identifisere hvilken side på nettstedet som vises i hver enkelt fane.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/78472749/161248718-328e303b-d97d-44ed-9388-5bf0f3b29a0b.png">

Fordi vi noen steder påtvinger brukeren at en side vises i ny fane (f.eks. i ansatt-tabellen, når man åpner egen side med detaljert info for en ansatt), bør vi nok også gjøre det enklere for brukeren å håndtere mange åpne faner for nettstedet.

Dette kan relativt enkelt gjøres f.eks. ved å bruke biblioteket [`react-helmet-async`](https://www.npmjs.com/package/react-helmet-async).

Forslag til noen sidetitler:
* Ansatt-siden: "Ansatte – Knowit Folk"
* En enkelt ansatt: "Fornavn Etternavn – Knowit Folk"
* Kunder, liste: "Kunder - Knowit Folk"
* Kunder, oversikt: "Oversikt kunder – Knowit Folk"
* Enkeltkunde: "Kundenavn – Knowit Folk"

**Comment by VegardHesselberg** [comment]
Jepp, dette virker som en god idé. Kan ikke se så mye å gjøre for å forbedre.

Jeg slengte sammen noe kjapt her for å illustrere hvordan det kommer til å se ut, i tillegg til noen andre sider som kommer i fremtiden:
https://www.figma.com/file/a6iR6JmiZblJRydhHfvjzz/Folk.knowit.no?node-id=1800%3A24104&t=fgppDodXNtYyJo5R-4

**Comment by rauboti-knowit** [comment]
Etter React 16.8 er dette mulig å gjøre med document.title = 'Din sidetittel her'. Har kikka litt rundt, og valgt å bruke dette som løsning fordi et nytt bibliotek for å kun endre 1 ting i header fort kan bli overkill (og introduserer dermed nye dependencies uten at det egentlig er noen grunn til at det er nødvendig).
