### ISSUE TITLE
Kompetansesøk basert på data fra CVPartner

### ISSUE THREAD

**Issue by HeleneSemmerud** [knowit/folk-webapp#363]
Som bruker av folk-appen ønsker jeg å kunne finne ut hvilke ansatte som kan hvilke teknologier. 
Til dette vil jeg i dag brukt cvpartner, da søk i folk-appen kun inneholder kategorier fra kompetansekartleggingen.

- Hvordan skal kompetanse som man lister i cvpartner vektes i søk (3 - 4 brukbar kompetanse)

**Comment by torjohannessen** [comment]
Lukkes foreløpig , nytt issue kan lages ved behov
