### ISSUE TITLE
Ekspress view - prosjektstatus

### ISSUE THREAD

**Issue by Greggy250** [knowit/folk-webapp#376]
Vist på felles demo i to versjoner den 15.10. 

Det er per dags dato to tabellkontekster, prosjektstatus og konsulentkompetanse. Disse opptrer på respektive Ansatte og Kompetanseside. I dette eksempelet står man på kompetansesiden men ønsker å vite om konsulenten er ledig eller opptatt ressurs uten å måtte navigere seg til Ansatte siden. Man klikker på konsulentbildet og får en transparent fargeoverlay på selve bildet som angir om konsulenten er en ledig eller opptatt ressurs (rød eller grønn). Når man klikker igjen går det tilbake til default view. Konsulentbildet man klikker for å få statusfarge ekskluderes fra hit area som ekspanderer og lukker konsulentfeltet. (det er inkludert i dag)

Det er to ekspress view versjoner, knowit/folk-webapp#377 er mer kompleks og viser mer. 

Spec.
https://xd.adobe.com/view/6339a9bc-e31f-4c25-97a0-18077d32059c-366a/screen/ff4dbcf3-64dd-488e-9ed0-18ec8cb47ef2/

![Knowit Folk - prosjektstatus ekspress](https://user-images.githubusercontent.com/67268611/97406912-38470080-18fa-11eb-899c-99d2e7d8948d.gif)

**Comment by henrikav** [comment]
Udatert
