### ISSUE TITLE
Personlig kompetanse profil radardiagram gir white out

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#392]
På en enkelt person sin Kompetansekartlegging fungerer defaulten (Stolpediagram), mens hvis man velger radardiagram og det er mer enn 9 områder så går folk i "white out". Ser ut til at når det er få søyler går det bra. 
Mulig feil når det er for mange områder.

**Comment by kjell-r** [comment]
Sjekk om denne blir løst av #391
