### ISSUE TITLE
Kompetanse - radar diagram problem

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#397]
Problem med at radarens strek ikke går hele veien rundt , men stopper ved nullverdier.
Radardiagram for kompetansekartlegging, både for enkeltpersoner og for akkumulert oversikt Kompetanse/kompetanseområder:
Når det er null i verdi stopper den sirkulære streken, her bør alle null verdier antagelig settes til 0 i stedet.
I øyeblikket synlig for "Softskills" og "Cybersikkerhet"

![image](https://user-images.githubusercontent.com/7239092/221865272-6fecb4f7-6c56-4583-aa3c-8aef33f80da8.png)

**Comment by larsgus** [comment]
Den underliggende årsaken her er at radar diagrammet kun er laget for å fungere med spørsmål som har type: "knowledgeMotivation". Alle spørsmål på softskills kategorien og et spørsmål på cybersikkerhet kategorien bruker type: "customScaleLabels". Disse har ikke dimensjonene knowledge og motivation, og gir dermed ikke mening å innkludere i diagrammet. Vi burde eksludere disse spørsmålene fra averageCompetenceAndMotivation rapporten.

**Comment by larsgus** [comment]
La til AND q.type = 'knowledgeMotivation' i spørringen for rapporten, ser ut til å fikse problemet.
```sql
SELECT competence, motivation, c.subCategory, c.category
FROM (SELECT AVG(a.knowledge) AS competence, q.topic as subCategory, c.text as category
      FROM kompetansekartlegging_answers AS a
               INNER JOIN kompetansekartlegging_questions AS q ON a.questionid = q.id
               INNER JOIN kompetansekartlegging_categories AS c ON q.categoryid = c.id
      WHERE c.text != 'Jobbrotasjon'
      GROUP BY q.topic, c.text) as c
         INNER JOIN (SELECT AVG(a.motivation) AS motivation, q.topic as subCategory, c.text as category
                     FROM kompetansekartlegging_answers AS a
                              INNER JOIN kompetansekartlegging_questions AS q ON a.questionid = q.id
                              INNER JOIN kompetansekartlegging_categories AS c ON q.categoryid = c.id
                     WHERE c.text != 'Jobbrotasjon'
                       AND q.type = 'knowledgeMotivation'
                     GROUP BY q.topic, c.text) as m ON c.subCategory = m.subCategory and c.category = m.category;
````

![image](https://user-images.githubusercontent.com/6408068/223116268-a66d1bd2-f859-46b6-aa15-de69b978d890.png)

**Comment by larsgus** [comment]
Men vi må nok gjøre tilsvarende for andre rapporter
