### ISSUE TITLE
Videreutvikling av Organisasjonsstruktur

### ISSUE THREAD

**Issue by henrikav** [knowit/folk-webapp#407]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Funksjonaliteten er ikke relatert til et problem.

**Beskriv løsningen du ønsker**
En videreutvikling av Organisasjonsstruktur i henhold til design. Se [her](https://www.figma.com/file/a6iR6JmiZblJRydhHfvjzz/Folk.knowit.no?node-id=1651%3A9388&t=B0vK3JPhMpxHSicV-0) for design. 

**Beskriv eventuelle alternativer du har vurdert**
Hvis du har ideer om alternative måter å løse eller designe denne siden på, ta gjerne kontakt med Vegard Hesselberg som har laget designet.

**Comment by torjohannessen** [comment]
Vær obs på at i AD kan vi ha navnproblemer ved at noen har ulikt navn  som person og som Manager. Hvis vi oppdager dette bør vi melde i fra til Henrik (HRJ) slik at feilen rettes opp i kilden.

**Comment by larsgus** [comment]
Jeg opplever [nettverksgrafen til nivo](https://nivo.rocks/network/) som noe begrenset. Vi har liten mulighet til å tweake layout og posisjonere noder slik at det blir et fornuftig organisasjonkart. Det er heller ikke mulig å zoome eller flytte viewet. 

For å oppnå designet fra Figma ville jeg kanskje vurdert å se på et annet bibliotek. Noen kjappe eksempler jeg fant var [Cytoscape](https://js.cytoscape.org/), [React Flow](https://reactflow.dev/) eller [React Sigma](https://sim51.github.io/react-sigma/)

**Comment by henrikav** [comment]
Hvis du har funnet alternative måter å visualisere strukturen på så synes jeg du skal utforske de slik at vi kan se hva som funker best. Trenger ikke bruke altfor mye tid på å forsøke å få Nivo til å funke hvis det finnes andre klart bedre alternativer
