### ISSUE TITLE
Legge til mulighet for å spesifisere tidsperiode i graf

### ISSUE THREAD

**Issue by mariehessen** [knowit/folk-webapp#422]
Starte å legge til features fra det nye designet. #381 

Man skal også kunne angi kalender-periode for at brukeren skal kunne spesifisere det mer nøyaktig etter det brukeren har behov for. 

![Image](https://user-images.githubusercontent.com/21339793/223985366-0ec2c4e9-2cf3-4c7e-81fd-3fae258c3cef.png)

Hvis det er mulig: 
- Ukesvelger (eller at den datoen man velger automatisk velger den uka). Siden man håndterer faktureringsuker er det mest naturlig å bruke det som valg og minste enhet.
- Periodisering. (Ukestart og månedsskifte)
- Skrive inn dato i tekstfelt for å angi datoer.
- Vise hvilke datoer som ikke er tilgjengelig (i fremtiden). 

![Image](https://user-images.githubusercontent.com/21339793/223983925-fc250377-66a8-4143-a6f3-a63b9fb1ec0c.png)

**Comment by EirikOsnes** [comment]
Arbeidet er påbegynt - det er laget en PR som lager en komponent i #446, men denne er ikke koblet opp mot å endre det faktiske filteret.
