### ISSUE TITLE
Oversikt over kunder som vises i grafen visualisert med kort

### ISSUE THREAD

**Issue by mariehessen** [knowit/folk-webapp#423]
Starte å legge til features fra det nye designet. #381 

Når bruker har valgt kunder i kundefilteret, vil informasjon om kundene visualiseres i kort under grafen. 

Elementene i "Kunder i graf i angitt periode" oppdateres basert på hvilke kunder som er valgt i filteret i listen til høyre. 

![Image](https://user-images.githubusercontent.com/21339793/223987533-b63c0075-4916-4504-aa4c-32f58eddaf16.png)

Angitt periode skal spesifisere hvilke periode det er. Enten datoer, måned kvartal eller år. 

![Image](https://user-images.githubusercontent.com/21339793/223989388-532bc2b0-8804-41c2-bb3e-6b7cf0c2d6ac.png)

**Comment by larsgus** [comment]
Dette er litt problematisk fordi kundene i grafen ikke nødvendigvis er de samme som er på kortene. Dette fordi det både er ulke navn på noen av kundene og fordi grafen har med historisk data som ikke kortene viser. 

@torjohannessen Hvordan synes du vi burde løse problemet med at grafen viser historisk data? Burde vi hatt kort for historiske kunder også?

![image](https://user-images.githubusercontent.com/6408068/232470670-9bfafe94-ebf1-4d62-a3c2-cbcfafce55f1.png)

**Comment by henrikav** [comment]
Henger sammen med https://github.com/knowit/folk-webapp/issues/424
