### ISSUE TITLE
Org.strukturen: ønske om kollapse alle under en manager

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#434]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
For å øke oversikten er det ønske om å kunne kollapse alle ansatte under en manager.
Det er også mulig at det er ønskelig å kollapse alle på nederste nivå - eller noe lignende

**Beskriv løsningen du ønsker**
Bør kanskje sjekkes ut med designer og prod.eiere.

**Beskriv eventuelle alternativer du har vurdert**
Konkret beskrivelse av alternativ løsning på problemet.

**Ekstra beskrivelse**
Legg til ekstra informasjon som screenshots eller lignende.

Update:
Kunne kollapse/skjule alle ansatte på ytterste lag av organisasjonsstrukturen, så kun lederne og gruppeledere er synlig. (feks. et filter øverst som skjuler alle gruppebarn) Og så kunne klikke på en spesifikk gruppeleder for å få opp kun personene som ligger under denne gruppelederen. Eller noe lignende.

**Comment by larsgus** [comment]
Hvem fremmet ønsket? Greit å vite litt mer om hvordan de så det for seg

**Comment by mcfremst** [comment]
Trenger design for dette. Burde også ha et møte

**Comment by torjohannessen** [comment]
Jeg ønsker at vi når vi kollapser noen / alle bør de som er kollapset vise et antall i parentes bak navnet slik at vi vet hvor mange "barn" som finnes når vi åpner.
