### ISSUE TITLE
Feil kunde på ansatt-oversikt hos noen ansatte

### ISSUE THREAD

**Issue by henrikav** [knowit/folk-webapp#445]
**Beskriv feilen**
Det fremstår som om vektingen til hvilket kundeprosjekt som vises for en ansatt ikke funker helt. 

**Forventet oppførsel**
Her skal egentlig riktig kunde vises basert på hva man har registrert flest timer på de siste ukene. Det er nok noe som ikke stemmer med måten dette gjøres på nå og burde undersøkes nærmere. Kan virke som den bare baserer seg på siste uke.

**Comment by torjohannessen** [comment]
Lukkes siden dette er rikitg
