### ISSUE TITLE
Undersøke og fikse sikkerhetsproblemer 

### ISSUE THREAD

**Issue by henrikav** [knowit/folk-webapp#472]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
For å øke sikkerheten og unngå svakheter i kodebasen så burde vi undersøke hvilke alternativer under "Security" på repoet som kan aktiveres. Dependabot har en del varsler allerede på svakheter som må følges opp også

**Comment by rauboti** [comment]
@henrikav De som ligger der er litt kinkige, og dreier seg om pakkene json5 (#55), loader-utils (#46, #47), minimatch (#43), d3-color (#41) og xml2js(#63). Det er dependancies til pakker installert av oss (eller dependancies av dependancies osv). Det ser ut til at Dependabot ikke har klart lage PR på disse fordi det ikke er nyere versjoner av libraries som er i bruk hvor disse dependancies er bumpet, og da er det en risiko for at noe knekker dersom kun dependancy bumpes. Jeg har prøvd å retrye dependabot på disse (ettersom de er noen måneder gamle) men uten hell på automatikken, iallefall.

En mulig måte å angripe det på, er å gå igjennom resten av libraries vi har. F.eks. bruker vi minimumversjon 0.8.0 av nivo. Den har en versjon 0.8.3, publisert 16 dager sida, og bl.a. nivo/core bruker d3-color hvor versjonen i 0.8.3 er satt til en som ikke lenger har problemet i dependabot security issue nr 41.
Det blir en mer ekstensiv gjennomgang, men det kan kanskje kvitte oss med noe av det på kort sikt. På lengre sikt kan det ev. vurderes å aktivere automatiske oppdateringer i dependabot (igjennom bruk av dependabot.yml fil som sjekkes inn i repoet), men da har man også risikoen for at ting knekker uten at vi tar i det, så spørs om det egentlig gir mer hodebry enn gevinst)

Hva tenker du?

**Comment by henrikav** [comment]
Veldig god vurdering og bra beskrevet. Jeg tenker da at vi dropper automatiske oppdateringer for å unngå at ting potensielt brekker til tilfeldige tider. Likevel synes jeg at vi burde gjøre en manuell gjennomgang av hvilke ting som kan oppdateres, som du sier. Tenker vi fortløpende kan gjøre slike gjennomganger og øke versjoner i henhold til det som dukker opp fra dependabot.

**Comment by rauboti** [comment]
Da bør vi gjennomgå hvilke pakker som bruker følgende libraries som dependancies, se om de har nyere versjoner hvor dependancyet er bumpet til ny nok versjon og se om de lar seg oppgradere før Security issuet ev. kan lukkes:
- [ ] json5, ref Security issue 55
- [ ] loader-utils, ref Security issue 46 og 47
- [ ] minimatch, ref Scurity issue 43
- [ ] d3-color, ref Scurity issue 41
- [ ] xml2js, ref security issue 63

**Comment by rauboti** [comment]
minimatch er dependancy for 9 pakker:
- 6 av dem ender opp i react-scripts v5.0.1 (som allerede er nyeste versjon)
- 2 av dem ender opp i serverless v3.25.1 (som har nyere pakker, men ikke hvor minimatch versjon er bumpet)
- Siste ender opp i folk-webapp@workspace, som er uversjonret og "vår egen", via pakken pretty-quick v3.1.3

**Comment by rauboti** [comment]
loader-utils er dependancy for 7 pakker. Alle ender opp i react-scripts v5.0.1 (som allerede er nyeste versjon)

**Comment by rauboti** [comment]
json5 er dependancy for 3 pakker (hvorav 6 versjoner av en av dem). Alle 3 ender opp i react-scripts v5.0.1 (som allerede er nyeste versjon)

**Comment by rauboti** [comment]
Som en foreløpig konklusjon; resten er nå i bruk av react-scripts v5.0.1 og serverless v3.25.1. Pakken react-scripts har ikke nyere versjoner enn v5.0.1, og dermed vil den uansett referere og bruke json5, loader-utils og minimatch versjoner som dependabot gir alarm på. Serverless har nyere versjoner, men heller ikke i nyere versjoner er minimatch osv bumpet til en versjon som fikser svakhetene dependabot har påpekt.

Etter avtale med @henrikav blir derfor denne lukket i denne omgang.
