### ISSUE TITLE
Universell utforming / oppdatering av tabell brukt på Ansatt- og Kundesidene

### ISSUE THREAD

**Issue by rauboti** [knowit/folk-webapp#476]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Tabellene i dagens form bærer preg av å ha blitt trikset til litt. Dette kan gjøre vedlikehold av koden vanskelig, men er heller ikke nødvendigvis bra mtp universell utforming.

**Beskriv løsningen du ønsker**
Ettersom vi har brukt MUI jevnt over i store deler av applikasjonen, gir det mening å også benytte MUI til visualiseringen av ansatte (både under kunder og i felles liste). Da vil også universell utforming i stor grad være løst, men i tillegg vil det kunne gjøre koden mer lesbar og kanskje også gjøre det mulig å flytte noe mer av stylingen ut av komponentene og inni theme.tsx-fila.
Visuelt bør vi ikke gjøre for store forskjeller fra slik det er i dag, så bakgrunnsfarger, bredder osv bør beholdes i så stor grad det er mulig inntil vi får andre instruksjoner fra design. Dette handler altså mer om selve koden.
Bruk følgende komponenter som utgangspunkt for omskrivingen:
- https://mui.com/material-ui/api/accordion/
- https://mui.com/material-ui/api/table/

Begge disse har også ferdige komponenter som kan brukes sammen med dem (som AccordionSummary, TableHead, TableBody, TableCell osv).

**Comment by tfahsing** [comment]
Jeg ser gjerne på denne
