### ISSUE TITLE
Kunder/"Overordnet oversikt" antall konsulenter

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#477]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Ønske av å kunne se "antall konsulenter hos kunden"  i tillegg til timer.

**Beskriv løsningen du ønsker**
I dag vises antall timer som en graf, kanskje antall konsulenter kan være stolper (eller en egen kurve i samme graf)- slik at vi ser forskjell på timer og personer(konsulenter) - hvis mulig.

**Beskriv eventuelle alternativer du har vurdert**
Ønsker en knapp som slår på det som vises. Default som i dag - timer, og vise dette ved at timer er slått på.
Det skal bare vises unike personer som har vært hos kunden i den angitte uke/måned.

**Ekstra beskrivelse**

**Comment by OliverKnowit** [comment]
Tror denne er gjort?
