### ISSUE TITLE
Fikse kundernavn under grafen på kundesiden

### ISSUE THREAD

**Issue by mcfremst** [knowit/folk-webapp#483]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Når kunder er valgt i grafen på kundesiden så blir teksten under med kundenavn veldig rotete og oppi hverandre. Dette skjer allerede når det er 3 kunder i grafen.

**Beskriv løsningen du ønsker**
Gjøre dette litt mindre rotete som vist i det ene bilde under fra figma. 

**Ekstra beskrivelse**
<img width="1167" alt="Screenshot 2023-05-23 at 11 59 59" src="https://github.com/knowit/folk-webapp/assets/58398217/ed7186cb-a2d1-48da-8d2e-cbf7083ff8e5">
<img width="877" alt="Screenshot 2023-05-23 at 12 02 40" src="https://github.com/knowit/folk-webapp/assets/58398217/0fa6a14f-f430-4bd3-9a89-f3636a7ae8d3">
<img width="386" alt="Screenshot 2023-05-23 at 12 03 01" src="https://github.com/knowit/folk-webapp/assets/58398217/8f0c45fc-518a-45fd-a449-19e69d5dbcb4">

**Comment by OliverKnowit** [comment]
Dette er fikset
