### ISSUE TITLE
Flere irrelevante resultat ved søk på ansatt i kundeside

### ISSUE THREAD

**Issue by palmanshaus** [knowit/folk-webapp#518]
**Beskriv feilen**
I listevisning over kunder kan man søke etter både ansatte og kunder. Hvis man søker etter en ansatt til stede hos gitt kunde vil man få opp denne, men også alle ansatte hos kunden

**Hvordan reprodusere feil**
Søk for eksempel på Einar i dev-data
Får da opp Einar og Fredrik under Entur AS når vel Fredrik som ikke matcher resultatet burde gjemmes

![image](https://github.com/knowit/folk-webapp/assets/129747871/cc3e258e-afce-49aa-a5a6-8ade44be32e2)

**Comment by OliverKnowit** [comment]
Nei, dette er ikke et ansatt filter, men et kundefilter

**Comment by palmanshaus** [comment]
> Nei, dette er ikke et ansatt filter, men et kundefilter

@OliverKnowit 
Da burde det vel isåfall uansett ikke kommet opp noe om man søker på feks Einar som i gitt case, så noe bør det nok fikses på med et slikt evt filter

**Comment by torjohannessen** [comment]
Lukker denne siden det er nye test data som er mere konsistent og denne feilen ikke finnes lenger
