### ISSUE TITLE
Error på Eirik Valens bilde

### ISSUE THREAD

**Issue by KristianFlock** [knowit/folk-webapp#541]
Beskriv feilen
Error i konsoll angående bilde til Eirik Valen, får en link men eksisterer ikke et bilde

Hvordan reprodusere feil
Åpne folk og se i kosollen på errorer

Forventet oppførsel
Ingen error

Ekstra kontekst
Legg ved skjermbilde eller tilleggsinformasjon.

**Comment by torjohannessen** [comment]
Eirik Valen er en av de som ikke har bilde i CV partner- så dette er ikke en bug
