### ISSUE TITLE
Konsistent mellom "Antall konsulenter" og de som vises bør stemme

### ISSUE THREAD

**Issue by torjohannessen** [knowit/folk-webapp#550]
**Beskriv feilen**
For Kunder/Overordnet oversikt er det for noe kunder ikke samsvar mellom "Antall konsulenter og det antallet som blir vist.
Dette bør være konsistent.

**Hvordan reprodusere feil**
For kunden Kommuneforlaget AS" vises for uke 50:
<img width="229" alt="image" src="https://github.com/knowit/folk-webapp/assets/7239092/e0ea1c36-cf98-4741-a22b-c9b6a5c2fe0c">
 mens det bare er 3 konsulenter som vises på oversikten under:
 
<img width="769" alt="image" src="https://github.com/knowit/folk-webapp/assets/7239092/f5a42faf-a680-4220-957d-718109c92bc7">

Andre eksempler er Statsbygg med 1 i Antall konsuenter mens det ikke vises noen ved trykk på kanppen øverst til høyre i her.
<img width="582" alt="image" src="https://github.com/knowit/folk-webapp/assets/7239092/c7ffa7f9-0d10-405a-9a1c-f1ec8892c26f">

**Forventet oppførsel**
Jeg forventer at antall konsulenter er det samme som de som vises.
Mulig at det er noe med perioder som bør justeres eller endres slik at det blir enklere.
Er det datamismatch bør det justers i databricks (lag nytt issues repoet til databricks på: https://github.com/Knowit-Objectnet/databricks/issues)

**Ekstra kontekst**
Legg ved skjermbilde eller tilleggsinformasjon.

**Comment by larsksy** [comment]
Dette problemet kommer av at `CustomerCard` (kortet som viser fakturerte timer) og `EmployeeTable` (tabellen med konsulenter) beregner antall konsulenter på forskjellig måte.

CustomerCard bruker UBW data til å beregne antall konsulenter. Når det står 4 konsulenter under KF er dette fordi 4 forskjellige personer har registrert timer i UBW under KF i løpet av de siste 3 registrerings-periodene. Tor Johannesen selv var en av disse da jeg sjekket, så Tor er tellt her som en konsulent siden han registrerte noen timer på KF en gang for ikke lenge siden.

EmployeeTable bruker data fra en fil som heter `basicEmployeeInformation` i dataplattform. I denne dataen ligger et felt som heter `primary_customer` som den bruker til å finne hvem som jobber hvor. Tabellen med konsulenter teller dermed kun konsulentene som har registrert KF som hovedkunde. Tor Johannesen har ikke KF som hovedkunde, så han dukker ikke opp i listen. Usikker på hva som skal til for at en ansatt får en hovedkunde registrert, siden salgsfolk i Knowit også dukker opp i listen av og til. Det er noe som skjer i dataplattformen som styrer dette, men jeg har ikke innsikt i det.  

Hverken `CustomerCard` eller `EmployeeTable` kan sies å være feil, de bare teller konsulenter på forskjellig måte. Å fikse dette problemet vil innebære å endre CustomerCard til å kun telle konsulenter med KF som hovedkunde, på samme måte som `EmployeeTable` gjør. Dette burde være fullstendig mulig, men kan være noe misvisende siden `Fakurerte timer forrige periode` da vil vise data for konsulenter som ikke er tellt med. 

En annen løsning kan være å endre beskrivelsen av feltet i `CustomerCard` til å presisere at dette er antall personer som nylig har registrert timer hos kunden, og ikke nødvendigvis fulltidskonsulenter som jobber der. 

Det burde antageligvis diskuteres litt rundt hvordan dere vil håndtere problemet videre. Jeg jobber kun med dette i romjulen, så jeg har ikke lyst til å gjøre helt selvstendige endringer i hvilken data `CustomerCard` benytter seg av. Jeg sender dermed denne saken videre til dere så dere kan drøfte hva beste løsningen på dette er, dere vet sikkert det bedre enn meg.

**Comment by OliverKnowit** [comment]
Har endret slik at antall konsulenter på kundesida teller alle konsulenter, og matcher de opp etter hvilken periode som er valgt i grafen. Lister også opp alle disse konsulentene på kundesida.
