### ISSUE TITLE
Implementere graf for t-formede kompetanseprofiler

### ISSUE THREAD

**Issue by cegknowit** [knowit/folk-webapp#605]
TLDR: T-formet kompetanseprofil grafen har blitt laget i Python kode, og tanken er å få det inn i Folk-prosjektet, hvor det må skrives om til Typescript.

Databricks instansen inneholder nå to tabeller relatert til kompetansekategorier. Tabellene oppdateres hver gang workflow jobbene kjøres:

* skills_mentioned_in_cvs inneholder alle kompetanseordene hentet fra alle konsulenters prosjekterfaring i CV Partner.
* skills_to_category_mapping oppdateres inkrementelt ved å spørre Azure ChatGPT API om hvor godt kompetanseordene matcher et forhåndsdefinert sett med kategorier (de samme kategoriene som kompetanse.knowit.no bruker).

Disse tabellene kan brukes til å tegne t-formede kompetanseprofil grafer for hver enkelt konsulent, eller for gjennomsnittskonsulenten, om det skulle være ønskelig.

Vi har python kode for å tegne grafene ved hjelp av gjenbrukbar spark SQL og plotly, men ingen som på det nåværende tidspunkt kan skrive frontend kode for folk.knowit.no. Det er dette som er arbeidsoppgaven.

Python koden kan kjøres i [denne databricks notebooken](https://dbc-a34fd897-2dce.cloud.databricks.com/?o=1686988473582720#notebook/725743835777168), dersom du har [koblet git repoet til databricks brukeren din](https://dbc-a34fd897-2dce.cloud.databricks.com/browse/folders/home?addGit=&o=1686988473582720&gitUrl=https%3A%2F%2Fgithub.com%2FKnowit-Objectnet%2Fdatabricks.git&gitProvider=gitHub). Kildekoden befinner seg også i [Databricks repoet](https://github.com/Knowit-Objectnet/databricks/blob/6d700646242fa00831c44a0a933f9fe74b3024ad/orgs/knowit/domains/folk/projects/cvai/flows/prep/skills/explore/t-shaped_competency_graph.py) for de som har tilgang der.

**Comment by p10trk** [comment]
Har lagt til en rapport på denne i https://github.com/Knowit-Objectnet/databricks/pull/137.

**Comment by p10trk** [comment]
Har tilpasset spørringen på Databricks (se egen pull-request), samt implementert henting og visning. Sikkert mulig å gjøre noe med design, da det ser ganske tettpakket med grafer på høyre siden. Men dette kan man gjøre i en ny sak. 

Datagrunnlaget er allerede generert i Databricks dev. Jeg testet i folk-webapp. Vedleggene viser hvordan kompetanseprofilen ser ut.
![Screenshot_20241212_153057](https://github.com/user-attachments/assets/f4fce2d2-7ea0-4977-b238-f5b6f5f990a2)
![Screenshot_20241212_154342](https://github.com/user-attachments/assets/6b5e582b-ab13-4b4c-824d-86d65301e0a9)
