### ISSUE TITLE
Side for ansatt laster ikke opp

### ISSUE THREAD

**Issue by joacimds** [knowit/folk-webapp#606]
**Beskriv feilen**
Dersom man er på siden med listen over de ansatte og bruker popup-knappen for å komme til den ansattes personlige side, så blir kun grafen lastet opp, men ingenting annet.

**Hvordan reprodusere feil**
F.eks.

1. Gå til [https://folk.knowit.no/ansatte](https://folk.knowit.no/ansatte).
2. Klikk på den firkantede boksen med pil til høyre for kolonnen med den ansattes navn.
3. En ny fane vil åpnes opp.
4. Denne siden vil ikke bli lastet opp som forventet

**Forventet oppførsel**
Siden med informasjon relatert til den ansatte skal lastes opp.

**Ekstra kontekst**
Dette er siden for [Adrian Pleym](https://folk.knowit.no/ansatt/adrian.pleym@knowit.no)

<img width="1240" alt="Screenshot 2024-08-14 at 08 26 57" src="https://github.com/user-attachments/assets/510259e8-37a2-4cea-9545-d0a80281e471">
ermbilde eller tilleggsinformasjon.

**Comment by karo** [comment]
Dette skjer også hvis man klikker på den ansatte fra organisasjonsstruktur

**Comment by karo** [comment]
Ser ut til at oppslaget går mot employeeProfile?email=XXXX når det feiler og employeeCompetence?email=XXXX når det funker, så dette kan vi nok få fiksa fra frontendsida.
