### ISSUE TITLE
Fag og hendelser bug

### ISSUE THREAD

**Issue by kroglid** [knowit/folk-webapp#615]
Oppsto en feil ved henting av data på "Fag og Hendelser"
Er referert til her:
https://github.com/orgs/knowit/projects/9/views/1?filterQuery=Fag+og+hendelser&pane=issue&itemId=17854825

Ser at dataplattform/client.ts#getReport kun blir kalt av denne, og får ikke noe kontakt med apiet
Finner heller ikke noe i s3

Kanskje bedre å fjerne "cardet", enn å bare vise en feilmelding hvis vi ikke har noe data på dette uansett

**Comment by torjohannessen** [comment]
Enig at vi kan fjerne dette kortet.
