### ISSUE TITLE
Visualisering i Knowit folk av t-profiler fra cvpartner

### ISSUE THREAD

**Issue by janhenrik** [knowit/folk-webapp#619]
I folk.knowit.no ønsker vi å vise t-profilene som er implementert i Databricks.

Se også: https://github.com/Knowit-Objectnet/ai-lab/issues/11

![Image](https://github.com/user-attachments/assets/0d7313da-1943-43f6-9d50-7da6b63dc5bf)

**Comment by cegknowit** [comment]
Se https://github.com/knowit/folk-webapp/issues/605 for flere detaljer.

**Comment by p10trk** [comment]
Løses i #605 .

**Comment by p10trk** [comment]
Det er ønskelig at visningen flyttes til egen fane i komponenten "Kompetansekartlegging", se bilde.
![t-formede kompetanseprofiler plassering](https://github.com/user-attachments/assets/e11aeb9a-6492-45d7-b2c2-71b11a9ac505)
